name: Backend Static Checks

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch: # 手動実行可能

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy bandit pytest
          pip install -e .

      - name: Lint and format check with Ruff
        run: |
          # リンティングとフォーマットチェックを行う
          ruff check .
          # フォーマットチェックのみを行う
          ruff format --check .

      - name: Type checking with mypy
        run: |
          mypy --ignore-missing-imports .

      - name: Security check with bandit
        run: |
          bandit -r . -x ./tests

      - name: Run tests
        run: |
          python -m pytest

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    needs: lint

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run migrations
        env:
          SECRET_KEY: test_key
          DEBUG: 1
          ALLOWED_HOSTS: localhost
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: app_test
          DB_USER: user
          DB_PASSWORD: password
        run: |
          python manage.py migrate

      - name: Test with pytest
        env:
          SECRET_KEY: test_key
          DEBUG: 1
          ALLOWED_HOSTS: localhost
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: app_test
          DB_USER: user
          DB_PASSWORD: password
        run: |
          python -m pytest
